kind: pipeline
name: com.kapeli.main

steps:
- name: fetch
  image: alpine/git
  environment:
    GIST_URL:
      from_secret: gist_url
  commands:
  - git clone https://github.com/Kapeli/feeds.git workspace/feeds
  - git clone https://github.com/Kapeli/Dash-X-Platform-Resources.git workspace/resources
  - git clone "$GIST_URL" workspace/gist

- name: process-feeds
  image: python:3-alpine
  commands:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install pypng
    - >-
      ./process_dash_feeds.py
      --manifest=docsets.json
      --blacklist=blacklist.json
      --resource-dir=workspace/resources
      workspace/feeds
      workspace/gist/docsets.json

- name: push
  image: alpine/git
  environment:
    GIT_NAME:
      from_secret: git_name
    GIT_EMAIL:
      from_secret: git_email
  commands:
    - cd workspace/gist
    - git diff
    - git config user.name "$GIT_NAME"
    - git config user.name
    - git config user.email "$GIT_EMAIL"
    - git commit -a -m"Update docsets"
    - git push
