kind: pipeline
name: com.kapeli.main

steps:
- name: fetch
  image: alpine/git
  commands:
  - git clone https://github.com/Kapeli/feeds.git workspace/feeds
  - git clone https://github.com/Kapeli/Dash-X-Platform-Resources.git workspace/resources
  - git clone https://gist.github.com/7d64124c24cacf6b29baacfa49f5be70.git workspace/gist

- name: process-feeds
  image: python:3-alpine
  commands:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install pypng
    - >-
      ./process_dash_feeds.py
      --manifest=docsets.json
      --blacklist=blacklist.json
      --resource-dir=workspace/resources
      workspace/feeds
      workspace/gist/docsets.json

- name: commit
  image: alpine/git
  commands:
    - cd workspace/gist
    - git diff
    - git config user.name $GIT_NAME && echo $?
    - git config user.email $GIT_EMAIL
    - printf "username=$GITHUB_TOKEN\n" | git credential fill
    - git commit -a -m"Update docsets"
    - git push
